### PR TITLE
chore: all-contributors configuration

### LINKED ISSUE #125: Chore: Add all-contributors bot configuration
## Description

As a maintainer,
I need to configure an all-contributors bot,
so that I can better recognize the contributors and leaders of this project.

   

-  https://allcontributors.org/docs/en/bot/configuration

### Update [Required]

- [ ] Add configuration to project https://allcontributors.org/docs/en/bot/configuration

 

- [ ]    Add first contributors to table

## Definition of Done

- [ ] All of the required items are completed.

    

- [x] Approval by 1 mentor.

## Estimation

1 hour

### PR DESCRIPTION
**Pull request by Aaishpra**
### Description

Add configuration for all-contributors

Fixes #125  

### Type of Change:

- Documentation

### How Has This Been Tested?

Tested by installing and adding files on my project : https://github.com/Aaishpra/musico

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by codesankalp — APPROVED** [review]

**Comment by isabelcosta** [comment]
I haven't yet quite figured out why on bridge in tech, @mtreacy002 can't run commands 🤔 I don't get how contributors cannot run it themselves.  Let me know the commands w/ contributors you'd like me to run for PRs to be created @Aaishpra

**Review by isabelcosta — APPROVED** [review]
awesome 🙌🏾

**Comment by Aaishpra** [comment]
> I haven't yet quite figured out why on bridge in tech, @mtreacy002 can't run commands thinking I don't get how contributors cannot run it themselves. Let me know the commands w/ contributors you'd like me to run for PRs to be created @Aaishpra

@isabelcosta we also need to add @keshakaneria for maintenance. Can you run the commands for adding her?
Thanks for adding me though. 😊

**Comment by keshakaneria** [comment]
> > I haven't yet quite figured out why on bridge in tech, @mtreacy002 can't run commands thinking I don't get how contributors cannot run it themselves. Let me know the commands w/ contributors you'd like me to run for PRs to be created @Aaishpra
> 
> @isabelcosta we also need to add @keshakaneria for maintenance. Can you run the commands for adding her?
> Thanks for adding me though. 😊

Thanks for the help @Aaishpra 😇

**Comment by isabelcosta** [comment]
Amazing @Aaishpra ! Thank you for letting me know, I just ran the command for it 🤗 @keshakaneria

**Pull request merged**
