### PR TITLE
fix: fix dependency conflict due to drf-jwt

### LINKED ISSUE #157: Remove djangorestframework-jwt as it is deprecated
### Describe the bug

While using python3.9 djangorestframework-jwt gives conflict with djangorestframework-simplejwt and the setup became complex.

### To Reproduce
1. Install by following steps in README.

### Expected behavior
No errors and simple installation.

### Screenshots
image

### Desktop (please complete the following information):
 - OS: Ubuntu & Windows
 - Browser Chrome

### Additional context
There is only one place where we are using djangorestframework-jwt:
https://github.com/anitab-org/anitab-forms-backend/blob/dd72f65ce5e43cb836be2b20572f51137dd8c518/token_auth/serializers/register.py#L3

Removing this will solve this issue.

### PR DESCRIPTION
**Pull request by moazfarrukh**
### Description

Fixes #157 

### Type of Change:

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue): fixes denpendency conflict caused by djangorestframework_jwt

### How Has This Been Tested?
I have tested this by running running tests using
python manage.py test
image
image

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have updated dependencies in `requirements.txt`

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by codesankalp — APPROVED** [review]
LGTM @moazfarrukh :+1:

**Review by Aaishpra — APPROVED** [review]
Thanks for solving this @moazfarrukh

**Comment by isabelcosta** [comment]
Thank you @Aaishpra and @codesankalp for reviewing this so timely 🤗

**Review by isabelcosta — APPROVED** [review]
Looks good! Thank you for contributing @moazfarrukh 🙌🏾

**Comment by moazfarrukh** [comment]
@isabelcosta my pleasure

**Pull request merged**
