### PR TITLE
typo: Fixed link in the README.md

### LINKED ISSUE #76: Mention the correct link to open session minutes on README
## Description

As a new contributor,
I need read the correct open session notes document (most current one),
so that I can be aware of most recent discussions.

The meeting minutes mentioned is the minutes from GSoC project sessions.
The new link is: https://docs.google.com/document/d/1JSyAr9bO4hJJxFvThvn_LVjW0KcEspXpzvWULRC_xJE/edit

### Update [Required]
- [ ] Add link to current open session minutes
- [ ] Correct the text with link to last gsoc meeting minutes, and refer to it as the old one

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

### PR DESCRIPTION
**Pull request by sahil9001**
### Description
Updated the new meeting link and marked the GSoC one as the old meeting minutes link.

Fixes #76 

### Type of Change:

- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have written Kotlin Docs whenever is applicable

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by sahil9001** [comment]
@codesankalp @isabelcosta

**Review by codesankalp — APPROVED** [review]

**Review by Rahulm2310 — COMMENTED** [review]
Good Job @sahil9001 🎉. Thanks for your contribution.

**Review by isabelcosta — APPROVED** [review]
Awesome work @sahil9001 !
Thank you for contributing!

**Comment by sahil9001** [comment]
Thanks @isabelcosta and @Rahulm2310  ! Looking forward to contribute more in future!

**Pull request merged**
