### PR TITLE
Made SendGrid email feature optional for development.

### LINKED ISSUE #85: Make sendgrid email feature optional for development
## Description
As a developer,
I need ease of development,
so that I can focus on feature development and avoid wasting thrid party resources for development.

At the moment, we are required to have a sendgrid account to work on the backend locally, and perhaps this is not necessary. If this is purely to send emails, these can be sent on the console. The idea is to make sendgrid usage optional. If we want to test the real feature, we can, if we don't need to receive real emails, then we don't need it.

For this you have to understand what is the exact usage of emails in the app. You can use environment variables to determine if this functionality should or not be used.

sendgrid: https://sendgrid.com/

### Update [Required]
- [ ] Document on README that using SENDGRID is optional
- [ ] Using sendgrid API key should be optional
- [ ] Write at least 1 test for this

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

### PR DESCRIPTION
**Pull request by codesankalp**
### Description

Added Console as `EMAIL_BACKEND` in `settings.py` which is the default for development to receiving the email.
Also updated the README.

Fixes #85

### Type of Change:

- Code
- Documentation

**Code/Quality Assurance Only**
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
By registering a new user the confirmation e-mail is sent to the standard output (terminal).

**Screenshot**:
email
 

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by codesankalp** [comment]
@isabelcosta @devkapilbansal Needs your review here.
I didn't add the test because EmailBackends are tested by Django itself.

**Review by isabelcosta — APPROVED** [review]
Looks amazing! Another approval and I can merge :)
Thank you so much for working on this @codesankalp !

**Review by devkapilbansal — APPROVED** [review]
LGTM :+1: 

Cc:- @isabelcosta

**Comment by devkapilbansal** [comment]
Adding Ready to Merge since there is no change in code

**Pull request merged**
